INSERT INTO TIPO_USUARIO (DESCRIPCION) 
VALUES 	('Admin');

INSERT INTO TIPO_USUARIO (DESCRIPCION) 
VALUES 	('Usuario');

INSERT INTO USUARIOS (USARIO, CLAVE, TIPO, CONDICION) 
VALUES 	('admin','1234',1,'Activo');

INSERT INTO USUARIOS (USUARIO, CLAVE, TIPO, CONDICION) 
VALUES 	('aldu', '1234',2,'Activo'),
		('rocio', '1234',2,'Activo'),
		('jenni', '1234',2,'Inactivo');
		
INSERT INTO ESTADO_TAREA (DESCRIPCION) 
VALUES ('Pendiente');

INSERT INTO ESTADO_TAREA (DESCRIPCION) 
VALUES ('Completa');

INSERT INTO MODO_TAREA (DESCRIPCION) 
VALUES ('Lectura');

INSERT INTO MODO_TAREA (DESCRIPCION) 
VALUES ('Escritura');

INSERT INTO TIPO_TAREA (DESCRIPCION) 
VALUES ('Privada');

INSERT INTO TIPO_TAREA (DESCRIPCION) 
VALUES ('Publica');

INSERT INTO TAREAS (DESCRIPCION, FECHA, CREADO_POR, IDESTADO, IDTIPO, IDMODO) 
VALUES ('CREAR BASE DE DATOS', '2017-04-16', 1, 1, 1, 2);

INSERT INTO TAREAS (DESCRIPCION, FECHA, CREADO_POR, MODIFICADO_POR, IDESTADO, IDTIPO, IDMODO) 
VALUES ('ACTUALIZAR BASE DE DATOS', '2017-04-17', 1, 2, 2, 1, 1);

--COMMIT;